apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-quota
spec:
  quota: 
    hard:
      pods: "10"
      requests.cpu: "4"
      requests.memory: 8Gi
      requests.ephemeral-storage: 20Gi
      limits.cpu: "6"
      limits.memory: 16Gi
      limits.ephemeral-storage: 20Gi
